# Generated by Django 5.2.6 on 2025-10-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='snapshot_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
