# Generated by Django 5.2.6 on 2025-11-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='session',
            name='chat_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
