# Generated by Django 5.2.6 on 2025-11-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_is_offline_available_session_is_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='strokes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='uploads_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
