# Generated by Django 5.2.5 on 2025-12-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_rename_message_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
