# Generated by Django 5.2.6 on 2025-10-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role_alter_customuser_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
