# Generated by Django 5.2.6 on 2025-11-24 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('session', '0002_rename_message_chatmessage_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('recipient', 'session', 'content', 'is_urgent')},
        ),
    ]
